---
# APT packages
- name: Install common packages
  apt:
    update_cache=yes
    state=latest
    name={{item}}
  with_items:
  - curl
  - wget
  - htop
  - vim
  - tree
  - software-properties-common
  - rsync
  - iptables-persistent
